// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"Dzaakk/simple-commerce/internal/product/handler"
	"Dzaakk/simple-commerce/internal/product/repository"
	"Dzaakk/simple-commerce/internal/product/routes"
	"Dzaakk/simple-commerce/internal/product/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *routes.ProductRoutes {
	productRepository := repository.NewProductRepository(db)
	productUseCase := usecase.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productUseCase)
	productRoutes := routes.NewProductRoutes(productHandler)
	return productRoutes
}
