// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"Dzaakk/synapsis/internal/product/handler"
	"Dzaakk/synapsis/internal/product/repository"
	product2 "Dzaakk/synapsis/internal/product/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *handler.ProductHandler {
	productRepository := product.NewProductRepository(db)
	productUseCase := product2.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productUseCase)
	return productHandler
}
