// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package transaction

import (
	"Dzaakk/synapsis/internal/customer/repository"
	"Dzaakk/synapsis/internal/shopping_cart/repository"
	"Dzaakk/synapsis/internal/transaction/handler"
	transaction2 "Dzaakk/synapsis/internal/transaction/repository"
	transaction3 "Dzaakk/synapsis/internal/transaction/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *transaction.TransactionHandler {
	transactionRepository := transaction2.NewTransactionRepository(db)
	shoppingCartRepository := shopping_cart.NewShoppingCartRepository(db)
	shoppingCartItemRepository := shopping_cart.NewShoppingCartItemRepository(db)
	customerRepository := customer.NewCustomerRepository(db)
	transactionUseCase := transaction3.NewTransactionUseCase(transactionRepository, shoppingCartRepository, shoppingCartItemRepository, customerRepository)
	transactionHandler := transaction.NewTransactionHandler(transactionUseCase)
	return transactionHandler
}
