// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	repository3 "Dzaakk/simple-commerce/internal/customer/repositories"
	repository4 "Dzaakk/simple-commerce/internal/product/repositories"
	repository2 "Dzaakk/simple-commerce/internal/shopping_cart/repositories"
	"Dzaakk/simple-commerce/internal/transaction/handlers"
	"Dzaakk/simple-commerce/internal/transaction/repositories"
	"Dzaakk/simple-commerce/internal/transaction/routes"
	"Dzaakk/simple-commerce/internal/transaction/usecases"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *routes.TransactionRoutes {
	transactionRepository := repository.NewTransactionRepository(db)
	shoppingCartRepository := repository2.NewShoppingCartRepository(db)
	shoppingCartItemRepository := repository2.NewShoppingCartItemRepository(db)
	customerRepository := repository3.NewCustomerRepository(db)
	productRepository := repository4.NewProductRepository(db)
	transactionUseCase := usecase.NewTransactionUseCase(transactionRepository, shoppingCartRepository, shoppingCartItemRepository, customerRepository, productRepository, db)
	transactionHandler := handler.NewTransactionHandler(transactionUseCase)
	transactionRoutes := routes.NewTransactionRoutes(transactionHandler)
	return transactionRoutes
}
