// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package shopping_cart

import (
	"Dzaakk/synapsis/internal/product/repository"
	"Dzaakk/synapsis/internal/shopping_cart/handler"
	shopping_cart2 "Dzaakk/synapsis/internal/shopping_cart/repository"
	shopping_cart3 "Dzaakk/synapsis/internal/shopping_cart/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *shopping_cart.ShoppingCarthandler {
	shoppingCartRepository := shopping_cart2.NewShoppingCartRepository(db)
	shoppingCartItemRepository := shopping_cart2.NewShoppingCartItemRepository(db)
	productRepository := product.NewProductRepository(db)
	shoppingCartUseCase := shopping_cart3.NewShoppingCartUseCase(shoppingCartRepository, shoppingCartItemRepository, productRepository)
	shoppingCarthandler := shopping_cart.NewShoppingCartHandler(shoppingCartUseCase)
	return shoppingCarthandler
}
