// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"Dzaakk/simple-commerce/internal/seller/handlers"
	"Dzaakk/simple-commerce/internal/seller/repositories"
	"Dzaakk/simple-commerce/internal/seller/routes"
	"Dzaakk/simple-commerce/internal/seller/usecases"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *routes.SellerRoutes {
	sellerRepository := repositories.NewSellerRepository(db)
	sellerUseCase := usecases.NewSellerUseCase(sellerRepository)
	sellerHandler := handlers.NewSellerHandler(sellerUseCase)
	sellerRoutes := routes.NewSellerRoutes(sellerHandler)
	return sellerRoutes
}
