// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"Dzaakk/simple-commerce/internal/seller/handler"
	"Dzaakk/simple-commerce/internal/seller/repository"
	"Dzaakk/simple-commerce/internal/seller/route"
	"Dzaakk/simple-commerce/internal/seller/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *route.SellerRoutes {
	sellerRepository := repository.NewSellerRepository(db)
	sellerUseCase := usecase.NewSellerUseCase(sellerRepository)
	sellerHandler := handler.NewSellerHandler(sellerUseCase)
	sellerRoutes := route.NewSellerRoutes(sellerHandler)
	return sellerRoutes
}
