// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"Dzaakk/simple-commerce/internal/customer/handler"
	"Dzaakk/simple-commerce/internal/customer/repository"
	"Dzaakk/simple-commerce/internal/customer/routes"
	"Dzaakk/simple-commerce/internal/customer/usecase"
	"database/sql"
)

// Injectors from wire.go:

func InitializedService(db *sql.DB) *routes.CustomerRoutes {
	customerRepository := repository.NewCustomerRepository(db)
	customerUseCase := usecase.NewCustomerUseCase(customerRepository)
	customerHandler := handler.NewCustomerHandler(customerUseCase)
	customerRoutes := routes.NewCustomerRoutes(customerHandler)
	return customerRoutes
}
